> **Copyright (c) 2020 Skymind Holdings Berhad**<br><br>
> **Copyright (c) 2021 Skymind Education Group Sdn. Bhd.**<br>
<br>
Licensed under the Apache License, Version 2.0 (the \"License\");
<br>you may not use this file except in compliance with the License.
<br>You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0/
<br>
<br>Unless required by applicable law or agreed to in writing, software
<br>distributed under the License is distributed on an \"AS IS\" BASIS,
<br>WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
<br>See the License for the specific language governing permissions and
<br>limitations under the License.
<br>
<br>
**SPDX-License-Identifier: Apache-2.0**
<br>

# Introduction

This notebook is to introduce the basic of Numpy in managing arrays. Numpy is a useful library which will be used all the time during the whole course. This tutorial consists of two major parts, which are:

1. Creating NumPy Array
2. Manipulating Numpy Array

# Notebook Content

* [Creating Arrays](#Creating-Arrays)
    * [0-Dimensional Arrays](#0-Dimensional-Array)
    * [1-Dimensional Arrays](#1-Dimensional-Array)
    * [2-Dimensional Arrays](#2-Dimensional-Array)
    * [3-Dimensional Arrays](#3-Dimensional-Array)
    * [Higher Dimensional Arrays](#Higher-Dimensional-Array)
    * [Array of Zeros](#Array-of-Zeros)
    * [Array of Ones](#Array-of-Ones)
    * [Array with Specific Number](#Array-with-Specific-Number)
    * [Identity Matrix](#Identity-Matrix)
    * [Array with Random Values](#Array-with-Random-Values)
    
    
    
* [Properties of ndarray](#Properties-of-ndarray)
    * [numpy.ndarray.shape](#numpy.ndarray.shape)
    * [numpy.ndarray.ndim](#numpy.ndarray.ndim)
    * [numpy.ndarray.size](#numpy.ndarray.size)
    * [numpy.ndarray.itemsize](#numpy.ndarray.itemsize)
    * [numpy.ndarray.dtype](#numpy.ndarray.dtype)
    
    
* [Access Element in Array](#Access-Element-in-Array)
    * [Get the first row](#Get-the-first-row)
    * [Get the first element](#Get-the-first-element)
    * [Get the 2nd element in the 3rd row](#Get-the-2nd-element-in-the-3rd-row)
    * [Retrieve list of elements](#Retrieve-list-of-elements)
    * [Boolean array indexing](#Boolean-array-indexing)
    

* [Array Slicing](#Array-Slicing)


* [Math Operation in ndarray](#Math-Operation-in-ndarray)
    * [Addition](#Addition)
    * [Subtraction](#Subtraction)
    * [Element-Wise Multiplication](#Element-Wise-Multiplication)
    * [Division](#Division)
    * [Matrix Multiplication](#Matrix-Multiplication)
    * [Square Root](#Square-Root)
    * [Sum All Elements](#Sum-All-Elements)
    * [Maximum Value](#Maximum-Value)
    * [Mean](#Mean)
    * [Standard Deviation](#Standard-Deviation)
    

* [Array Manipulation](#Array-Manipulation)
    * [Changing Shape](#Changing-Shape)
        * [numpy.ndarray.reshape](#numpy.ndarray.reshape)
        * [numpy.ndarray.flat](#numpy.ndarray.flat)
    * [Transpose Operations](#Transpose-Operations)
        * [numpy.ndarray.transpose](#numpy.ndarray.transpose)
        * [numpy.swapaxes](#numpy.swapaxes)
    * [Joining Array](#Joining-Array)
        * [numpy.concatenate](#numpy.concatenate)
        * [numpy.stack](#numpy.stack)

# Import Library

In [1]:
import numpy as np

SEED = 2021
np.random.seed(SEED)

# Creating Arrays

In [2]:
# Create ndarray
arr = np.array(['a', 'b', 'c', 'd'])

# Display array
print(arr)

# Show the datatype of arr
print(type(arr))

['a' 'b' 'c' 'd']
<class 'numpy.ndarray'>


### 0 Dimensional Array

In [3]:
# Also known as scalar
scalar = np.array(100)

# Display scalar vector
print(scalar)

# Show the dimension of scalar
print("Dimension:", scalar.ndim)

100
Dimension: 0


### 1 Dimensional Array

In [4]:
# Create 1D array
D1_arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Display 1D array
print(D1_arr)

# Show the dimension
print("Dimension:", D1_arr.ndim)

[1 2 3 4 5 6 7]
Dimension: 1


### 2 Dimensional Array

In [5]:
# Create 2D array
D2_arr = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Display 2D array
print(D2_arr)

# Show the dimension
print("Dimension:", D2_arr.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Dimension: 2


### 3 Dimensional Array

In [6]:
# Create 3D array
D3_arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

# Display 3D array
print(D3_arr)

# Show the dimension
print("Dimension:", D3_arr.ndim)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
Dimension: 3


### Higher Dimensional Array

In [7]:
# Create 5 dimension array
nd_arr = np.array(['S', 'K', 'Y', 'M', 'I', 'N', 'D'], ndmin=5)

# Display 5D array
print(nd_arr)

# Show the dimension
print("Dimension:", nd_arr.ndim)

[[[[['S' 'K' 'Y' 'M' 'I' 'N' 'D']]]]]
Dimension: 5


### Array of Zeros

In [8]:
# Required parameter shape in tuple
arr = np.zeros(shape=(2,2))

print(arr)

[[0. 0.]
 [0. 0.]]


### Array of Ones

In [9]:
# Required parameter shape in tuple
arr = np.ones(shape=(3, 4))

print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### Array with Specific Number

In [10]:
# Required parameter shape in tuple and fill_value
arr = np.full(shape=(4, 4), fill_value=6)

print(arr)

[[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]]


### Identity Matrix

In [11]:
# Required parameter N, Number of rows
arr = np.eye(N=2)

print(arr)

[[1. 0.]
 [0. 1.]]


### Array with Random Values

In [12]:
# Create a random valued array
arr = np.random.random(size=(4, 4),)

print(arr)

[[0.60597828 0.73336936 0.13894716 0.31267308]
 [0.99724328 0.12816238 0.17899311 0.75292543]
 [0.66216051 0.78431013 0.0968944  0.05857129]
 [0.96239599 0.61655744 0.08662996 0.56127236]]


# Properties of ndarray

### numpy.ndarray.shape
Get the current shape of an array

In [13]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Shape:", arr.shape)

Shape: (2, 3)


### numpy.ndarray.ndim
Number of array dimensions

In [14]:
print("Dimension:", arr.ndim)

Dimension: 2


### numpy.ndarray.size
Number of elements in the array.

In [15]:
print("Size:", arr.size)

Size: 6


### numpy.ndarray.itemsize
Length of one array element in bytes

In [16]:
print("Item Size in (byte):", arr.itemsize)

Item Size in (byte): 4


### numpy.ndarray.dtype
Data-type of the array’s elements

In [17]:
print("Item datatype:", arr.dtype)

Item datatype: int32


# Access Element in Array

In [18]:
# Use index to access the element in the array
arr = np.random.random(size=(4,4))

print(arr)

[[0.61652471 0.96384302 0.57430429 0.37116085]
 [0.45214524 0.20185025 0.56930512 0.19509597]
 [0.58370402 0.47631347 0.5178144  0.82309863]
 [0.73222503 0.06905627 0.67212894 0.64348481]]


### Get the first row

In [19]:
print("1st row:", arr[0])

1st row: [0.61652471 0.96384302 0.57430429 0.37116085]


### Get the first element

In [20]:
print("1st element:", arr[0, 0])

1st element: 0.6165247086179901


### Get the 2nd element in the 3rd row

In [21]:
print("2nd element in the 3rd row:", arr[2, 1])

2nd element in the 3rd row: 0.4763134735921163


### Retrieve list of elements

In [22]:
# Integer array indexing
print(arr[[0, 1, 2], [2, 1, 0]])

# Is similar to
print([arr[0, 2], arr[1, 1], arr[2, 0]])

[0.57430429 0.20185025 0.58370402]
[0.5743042944546707, 0.20185024783461958, 0.583704016323978]


In [23]:
rows = np.arange(4) # [0 1 2 3]
columns = [2, 3, 2, 1]

In [24]:
print(arr[rows, columns])

[0.57430429 0.19509597 0.5178144  0.06905627]


### Boolean array indexing

In [25]:
# Find the elements of a that are bigger than 0.5;
# this returns a numpy array of Booleans of the same
# shape as a, where each slot of bool_idx tells
# whether that element of a is > 0.5.

bool_idx = (arr > 0.5)
print(bool_idx)

[[ True  True  True False]
 [False False  True False]
 [ True False  True  True]
 [ True False  True  True]]


In [26]:
# Return all elements that more than 0.5 to a list
print(arr[bool_idx])

[0.61652471 0.96384302 0.57430429 0.56930512 0.58370402 0.5178144
 0.82309863 0.73222503 0.67212894 0.64348481]


# Array Slicing

In [27]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]

a = np.array([[1,2,3,4], 
              [5,6,7,8],
              [9,10,11,12]])

In [28]:
# Use slicing to pull out the subarray consisting of the first 2 rows with 2nd and 3rd columns
# b is the following array of shape (2, 2):

b = a[:2, 1:3]

print(b)

[[2 3]
 [6 7]]


In [29]:
# Assign the first element in b to 10
b[0, 0] = 10

print(b)

[[10  3]
 [ 6  7]]


In [30]:
# Two ways of accessing the data in the middle row of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the
# original array:
row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a

In [31]:
print(row_r1, row_r1.shape)

[5 6 7 8] (4,)


In [32]:
print(row_r2, row_r2.shape)

[[5 6 7 8]] (1, 4)


In [33]:
# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]

In [34]:
print(col_r1, col_r1.shape)

[10  6 10] (3,)


In [35]:
print(col_r2, col_r2.shape)

[[10]
 [ 6]
 [10]] (3, 1)


# Math Operation in ndarray

In [36]:
# Create a random int array with size=(4,4)

x = np.random.randint(0, high=99, size=(4,4))
y = np.random.randint(0, high=99, size=(4,4))

In [37]:
print("x:\n", x)
print("\ny:\n", y)

x:
 [[76 53 11 19]
 [33 78 17 89]
 [50  7 27 63]
 [51  9 25 71]]

y:
 [[84 27 75 27]
 [19 31 50 89]
 [27 18 53 32]
 [20 95 87  3]]


### Addition

In [38]:
# Matrix addition operation

z = x + y

In [39]:
print(z)

[[160  80  86  46]
 [ 52 109  67 178]
 [ 77  25  80  95]
 [ 71 104 112  74]]


In [40]:
# Addition with 1D array
arr = np.array([1, 2, 3, 4])

# Add arr to all rows in x
print(np.add(x, arr))

[[77 55 14 23]
 [34 80 20 93]
 [51  9 30 67]
 [52 11 28 75]]


In [41]:
# Addition with scalar value (broadcast)
num = 10

# Add 10 to all elements in x
print(np.add(x, num))

[[86 63 21 29]
 [43 88 27 99]
 [60 17 37 73]
 [61 19 35 81]]


### Subtraction

In [42]:
# Matrix subtraction operation

z = x - y

In [43]:
print(z)

[[ -8  26 -64  -8]
 [ 14  47 -33   0]
 [ 23 -11 -26  31]
 [ 31 -86 -62  68]]


In [44]:
# Subtraction with 1D array
arr = np.array([2, 4, 6, 8])

# Subtract arr to all rows in x
print(np.subtract(x, arr))

[[74 49  5 11]
 [31 74 11 81]
 [48  3 21 55]
 [49  5 19 63]]


In [45]:
# Subtraction with scalar value
num = 20

# Subtract 20 to all element in x
print(np.subtract(x, num))

[[ 56  33  -9  -1]
 [ 13  58  -3  69]
 [ 30 -13   7  43]
 [ 31 -11   5  51]]


### Element-Wise Multiplication

In [46]:
z = x * y
print(z)

[[6384 1431  825  513]
 [ 627 2418  850 7921]
 [1350  126 1431 2016]
 [1020  855 2175  213]]


In [47]:
# Multiplication with 1D array
arr = [2, 3, 4, 5]

# Element wise multiplication
print(np.multiply(x, arr))

[[152 159  44  95]
 [ 66 234  68 445]
 [100  21 108 315]
 [102  27 100 355]]


In [48]:
# Multiplication with scalar
num = 14

print(np.multiply(x, num))

[[1064  742  154  266]
 [ 462 1092  238 1246]
 [ 700   98  378  882]
 [ 714  126  350  994]]


### Division

In [49]:
# Element wise division
z = x / y

print(z)

[[ 0.9047619   1.96296296  0.14666667  0.7037037 ]
 [ 1.73684211  2.51612903  0.34        1.        ]
 [ 1.85185185  0.38888889  0.50943396  1.96875   ]
 [ 2.55        0.09473684  0.28735632 23.66666667]]


In [50]:
# Division with 1D array
arr = [1, 2, 1, 2]

print(np.divide(x, arr))

[[76.  26.5 11.   9.5]
 [33.  39.  17.  44.5]
 [50.   3.5 27.  31.5]
 [51.   4.5 25.  35.5]]


In [51]:
# Division with scalar
num = 2

print(np.divide(x, num))

[[38.  26.5  5.5  9.5]
 [16.5 39.   8.5 44.5]
 [25.   3.5 13.5 31.5]
 [25.5  4.5 12.5 35.5]]


### Matrix Multiplication

In [52]:
# Using np.dot to perform matrix multiplication
# Matrix 1: shape = (3,4)
# Matrix 2: shape = (4,2)
# Shape of M1 dot M2 = (3,2)

M1 = np.random.randint(0, 9, size=(3,4))
M2 = np.random.randint(0, 19, size=(4,2))

In [53]:
# Matrix multiplication
ans = M1.dot(M2)

print("Answer:")
print(ans)

print("\nShape:", ans.shape)

Answer:
[[ 78  89]
 [154 195]
 [167 193]]

Shape: (3, 2)


### Square Root

In [54]:
print(np.sqrt(x))

[[8.71779789 7.28010989 3.31662479 4.35889894]
 [5.74456265 8.83176087 4.12310563 9.43398113]
 [7.07106781 2.64575131 5.19615242 7.93725393]
 [7.14142843 3.         5.         8.42614977]]


### Sum All Elements

In [55]:
# Compute sum of all elements
print("Sum of all element in matrix x:", np.sum(x))

# Compute sum of each column
print("Sum of each column in matrix x:", np.sum(x, axis=0))

# Compute sum of each row
print("Sum of each row in matrix x:", np.sum(x, axis=1))

Sum of all element in matrix x: 679
Sum of each column in matrix x: [210 147  80 242]
Sum of each row in matrix x: [159 217 147 156]


### Maximum Value

In [56]:
print(x)

[[76 53 11 19]
 [33 78 17 89]
 [50  7 27 63]
 [51  9 25 71]]


In [57]:
# Maximum value in matrix x
print("Maximum value in matrix X:", np.max(x))

# Maximum value along the vertical axis
print("Maximum value along vertical axis(Column):", np.max(x, axis=0))

# Maximum value along the horizontal axis
print("Maximum value along the horizontal axis(Row):", np.max(x, axis=1))

Maximum value in matrix X: 89
Maximum value along vertical axis(Column): [76 78 27 89]
Maximum value along the horizontal axis(Row): [76 89 63 71]


### Mean

In [58]:
# Mean of all elements
print("Mean:", np.mean(x))

Mean: 42.4375


### Standard Deviation

In [59]:
# Compute the standard deviation
print("Standard Deviation:", np.std(x))

Standard Deviation: 26.492849860858684


# Array Manipulation

## Changing Shape

### numpy.ndarray.reshape
Gives a new shape to an array without changing its data.

In [60]:
arr = np.random.randint(0, 9, size=(3,2))

print(arr)

[[6 3]
 [1 3]
 [6 1]]


In [61]:
# Reshape to (2,3)
print(arr.reshape((2,3)))

[[6 3 1]
 [3 6 1]]


### numpy.ndarray.flat
A 1-D iterator over the array.

In [62]:
z = np.random.randint(0, 9, size=(10,10))

# Create a new copy of flatten array
print(z.flatten())

[8 0 5 0 7 0 1 3 6 4 7 4 1 7 1 4 6 6 7 4 5 2 3 2 0 0 7 4 6 1 7 4 4 7 4 3 7
 2 5 5 2 7 4 1 6 6 7 4 3 2 8 0 5 8 1 6 6 3 7 5 4 4 3 1 3 7 2 1 5 7 8 2 8 8
 7 8 3 0 3 3 8 3 1 5 7 2 0 2 2 7 1 0 1 6 3 2 2 2 3 3]


## Transpose Operations

### numpy.ndarray.transpose
Returns a view of the array with axes transposed.

In [63]:
arr = np.random.randint(0, 9, size=(3,2))

z = np.transpose(arr)
print(z)

print("\nShape:", z.shape, "\n")

# Similar function
print(arr.T)

[[5 0 8]
 [1 1 3]]

Shape: (2, 3) 

[[5 0 8]
 [1 1 3]]


### numpy.swapaxes
Interchange two axes of an array.

In [64]:
x = np.random.randint(0, 9, size=(4,4))

print(x)
print("Original shape:", x.shape)

[[0 1 1 4]
 [5 7 2 5]
 [0 2 6 6]
 [4 3 4 4]]
Original shape: (4, 4)


In [65]:
# Swap between axis 0 and 1, similar to transpose
y = np.swapaxes(x, 0, 1)

In [66]:
print(y)

[[0 5 0 4]
 [1 7 2 3]
 [1 2 6 4]
 [4 5 6 4]]


## Joining Array

In [67]:
x = np.random.randint(0, 9, size=(4,4))
y = np.random.randint(0, 9, size=(4,4))

In [68]:
print("x:")
print(x)

print("\ny:")
print(y)

x:
[[1 2 1 7]
 [4 4 1 0]
 [2 5 4 4]
 [7 4 8 1]]

y:
[[2 7 5 8]
 [5 3 0 5]
 [5 6 4 8]
 [8 4 5 8]]


### numpy.concatenate
Join a sequence of arrays along an existing axis.

In [69]:
# Vertically joined
print(np.concatenate((x,y), axis=0))

[[1 2 1 7]
 [4 4 1 0]
 [2 5 4 4]
 [7 4 8 1]
 [2 7 5 8]
 [5 3 0 5]
 [5 6 4 8]
 [8 4 5 8]]


In [70]:
# Horizontally joined
print(np.concatenate((x,y), axis=1))

[[1 2 1 7 2 7 5 8]
 [4 4 1 0 5 3 0 5]
 [2 5 4 4 5 6 4 8]
 [7 4 8 1 8 4 5 8]]


### numpy.stack
Join a sequence of arrays along a new axis.

In [71]:
# Vertically stack
print(np.stack((x,y), axis=0))

[[[1 2 1 7]
  [4 4 1 0]
  [2 5 4 4]
  [7 4 8 1]]

 [[2 7 5 8]
  [5 3 0 5]
  [5 6 4 8]
  [8 4 5 8]]]


In [72]:
# Horizontally stack
print(np.stack((x,y), axis=1))

[[[1 2 1 7]
  [2 7 5 8]]

 [[4 4 1 0]
  [5 3 0 5]]

 [[2 5 4 4]
  [5 6 4 8]]

 [[7 4 8 1]
  [8 4 5 8]]]


# Contributors

**Author**
<br>Chee Lam

# References

1. [Numpy Documentation](https://numpy.org/doc/stable/reference/index.html)
2. [Numpy Array Manipulation](https://www.tutorialspoint.com/numpy/numpy_array_manipulation.htm)
3. [NumPy Creating Arrays](https://www.w3schools.com/python/numpy/numpy_creating_arrays.asp)